import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'amit' at '9/6/16 11:48 AM' with Gradle 2.13
 *
 * @author amit, @date 9/6/16 11:48 AM
 */
public class LibraryTest {

}
